# Generated by Django 4.1.1 on 2022-10-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodAPI',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='Стоимость')),
                ('Quantity', models.IntegerField(blank=True, null=True, verbose_name='Кол-во товара')),
                ('QuantitySales', models.IntegerField(blank=True, null=True, verbose_name='Кол-во продаж товара')),
            ],
            options={
                'db_table': 'goodapi',
                'managed': False,
            },
        ),
    ]
